### ISSUE TITLE
Which virtualhome envronment(0-50) matches your scenarios?

### ISSUE THREAD

**Issue by lqiang2003cn** [microsoft/ChatGPT-Robot-Manipulation-Prompts#6]
I am using virtualhome 2.3.0. When i debug the following code:

`environment = populate_environment(graph, extract_objects(reference_program), "kitchen")`

the returned environment is not right. For example, the object <breadslice_311> is labelled as 'asset' and it's relationships with other objects just doesn't make sense. I wonder which virtualhome environment(0-50) did you use when designing your scenarios ?

I am pretty sure the code:

`reset(comm)`

just doesn't initiate the corrent environment, at least in my local setup.

Any suggestions? Thanks in adavance.

**Comment by Naoki-Wake** [comment]
We apologize for the delayed response and any confusion caused. Thank you for bringing this issue to our attention.

The issue you've encountered is due to a version mismatch in the VirtualHome simulator. The object names and IDs in this code are based on version 2.2.4, while our documentation incorrectly stated the use of version 2.3.0. We are in the process of updating our documentation to rectify this mistake. The VirtualHome simulator version 2.2.4 is available for download at the following link:
[VirtualHome Documentation - Downloads v2.2.4](http://virtual-home.org/documentation/master/downloads/downloads.html#v2-2-4)

Regarding your specific query, using the Python API virtualhome==2.3.0 is appropriate. However, as you rightly noted, the comm.reset command in this version is incompatible with the older simulator. Instead, [comm.post_command](https://github.com/microsoft/ChatGPT-Robot-Manipulation-Prompts/blob/48d8463392b61f176517e56512b09dca3ff57039/examples/task_decomposition_virtualhome/task_planning.py#L25) is being used to reset the environment. Additionally, we defaulted to using "scene 0" of the simulator. While the scene can be changed by specifying [scene_index](https://github.com/microsoft/ChatGPT-Robot-Manipulation-Prompts/blob/48d8463392b61f176517e56512b09dca3ff57039/examples/task_decomposition_virtualhome/task_planning.py#L24C17-L24C28), please be aware that there are only seven environments available in version 2.2.4 of the simulator.

On a separate note, we would like to inform you that this repository is compatible with openai==0.28.1, not the latest version openai==1.2.3.

We sincerely apologize for any inconvenience this has caused and hope that this clarification will help you. Should you have further questions or encounter additional issues, please feel free to reach out.

Best regards,
